# Generated by Django 4.1.3 on 2022-12-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Img', models.ImageField(upload_to='pics')),
                ('position', models.TextField()),
            ],
        ),
    ]
